item { 
	name:'botolplastik'
	id:1
}
item { 
	name:'botolkaca'
	id:2
}
item { 
	name:'plastik'
	id:3
}
item { 
	name:'kertas'
	id:4
}
item { 
	name:'kardus'
	id:5
}
item { 
	name:'sedotan'
	id:6
}
item { 
	name:'sterofoam'
	id:7
}
